# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Moov
  module Models
    module Components
    
      # AccountVerificationStatus - Possible states an account verification can be in.
      # 
      # @deprecated  class: This will be removed in a future release, please migrate away from it as soon as possible.
      class AccountVerificationStatus < T::Enum


        enums do
          UNVERIFIED = new('unverified')
          PENDING = new('pending')
          RESUBMIT = new('resubmit')
          REVIEW = new('review')
          VERIFIED = new('verified')
          FAILED = new('failed')
        end
      end
    end
  end
end
