# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Moov
  module Models
    module Components

      class ACHDebitTransferProcessingDetails
        extend T::Sig
        include Crystalline::MetadataFields


        field :trace_number, ::String, { 'format_json': { 'letter_case': ::Moov::Utils.field_name('traceNumber'), required: true } }

        field :return_, Crystalline::Nilable.new(Models::Components::ACHException), { 'format_json': { 'letter_case': ::Moov::Utils.field_name('return') } }

        field :correction, Crystalline::Nilable.new(Models::Components::ACHException), { 'format_json': { 'letter_case': ::Moov::Utils.field_name('correction') } }

        sig { params(trace_number: ::String, return_: T.nilable(Models::Components::ACHException), correction: T.nilable(Models::Components::ACHException)).void }
        def initialize(trace_number:, return_: nil, correction: nil)
          @trace_number = trace_number
          @return_ = return_
          @correction = correction
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @trace_number == other.trace_number
          return false unless @return_ == other.return_
          return false unless @correction == other.correction
          true
        end
      end
    end
  end
end
