# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Moov
  module Models
    module Components

      class Address
        extend T::Sig
        include Crystalline::MetadataFields


        field :address_line1, ::String, { 'format_json': { 'letter_case': ::Moov::Utils.field_name('addressLine1'), required: true } }

        field :city, ::String, { 'format_json': { 'letter_case': ::Moov::Utils.field_name('city'), required: true } }

        field :state_or_province, ::String, { 'format_json': { 'letter_case': ::Moov::Utils.field_name('stateOrProvince'), required: true } }

        field :postal_code, ::String, { 'format_json': { 'letter_case': ::Moov::Utils.field_name('postalCode'), required: true } }

        field :country, ::String, { 'format_json': { 'letter_case': ::Moov::Utils.field_name('country'), required: true } }

        field :address_line2, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Moov::Utils.field_name('addressLine2') } }

        sig { params(address_line1: ::String, city: ::String, state_or_province: ::String, postal_code: ::String, country: ::String, address_line2: T.nilable(::String)).void }
        def initialize(address_line1:, city:, state_or_province:, postal_code:, country:, address_line2: nil)
          @address_line1 = address_line1
          @city = city
          @state_or_province = state_or_province
          @postal_code = postal_code
          @country = country
          @address_line2 = address_line2
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @address_line1 == other.address_line1
          return false unless @city == other.city
          return false unless @state_or_province == other.state_or_province
          return false unless @postal_code == other.postal_code
          return false unless @country == other.country
          return false unless @address_line2 == other.address_line2
          true
        end
      end
    end
  end
end
