# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Moov
  module Models
    module Components

      class AmountDecimalUpdate
        extend T::Sig
        include Crystalline::MetadataFields

        # A 3-letter ISO 4217 currency code.
        field :currency, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Moov::Utils.field_name('currency') } }
        # A decimal-formatted numerical string that represents up to 9 decimal place precision. 
        # 
        # For example, $12.987654321 is '12.987654321'.
        field :value_decimal, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Moov::Utils.field_name('valueDecimal') } }

        sig { params(currency: T.nilable(::String), value_decimal: T.nilable(::String)).void }
        def initialize(currency: nil, value_decimal: nil)
          @currency = currency
          @value_decimal = value_decimal
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @currency == other.currency
          return false unless @value_decimal == other.value_decimal
          true
        end
      end
    end
  end
end
