# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Moov
  module Models
    module Components
    
      # ApplicationScope - A permission that the application requests on another account.
      class ApplicationScope < T::Enum


        enums do
          ACCOUNTS_READ = new('accounts.read')
          ACCOUNTS_WRITE = new('accounts.write')
          ANALYTICS_READ = new('analytics.read')
          APPLE_PAY_MERCHANT_READ = new('apple-pay-merchant.read')
          APPLE_PAY_MERCHANT_WRITE = new('apple-pay-merchant.write')
          APPLE_PAY_READ = new('apple-pay.read')
          APPLE_PAY_WRITE = new('apple-pay.write')
          BANK_ACCOUNTS_READ = new('bank-accounts.read')
          BANK_ACCOUNTS_WRITE = new('bank-accounts.write')
          CAPABILITIES_READ = new('capabilities.read')
          CAPABILITIES_WRITE = new('capabilities.write')
          CARDS_READ = new('cards.read')
          CARDS_WRITE = new('cards.write')
          DOCUMENTS_READ = new('documents.read')
          DOCUMENTS_WRITE = new('documents.write')
          FED_READ = new('fed.read')
          FILES_READ = new('files.read')
          FILES_WRITE = new('files.write')
          ISSUED_CARDS_READ = new('issued-cards.read')
          ISSUED_CARDS_WRITE = new('issued-cards.write')
          ISSUED_CARDS_READ_SECURE = new('issued-cards.read-secure')
          PAYMENT_METHODS_READ = new('payment-methods.read')
          PING_READ = new('ping.read')
          PROFILE_ENRICHMENT_READ = new('profile-enrichment.read')
          PROFILE_READ = new('profile.read')
          PROFILE_WRITE = new('profile.write')
          PROFILE_DISCONNECT = new('profile.disconnect')
          REPRESENTATIVES_READ = new('representatives.read')
          REPRESENTATIVES_WRITE = new('representatives.write')
          TRANSFERS_READ = new('transfers.read')
          TRANSFERS_WRITE = new('transfers.write')
          WALLETS_READ = new('wallets.read')
        end
      end
    end
  end
end
