# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Moov
  module Models
    module Components

      class BankAccountVerificationStatus < T::Enum
        enums do
          NEW = new('new')
          SENT_CREDIT = new('sent-credit')
          MAX_ATTEMPTS_EXCEEDED = new('max-attempts-exceeded')
          FAILED = new('failed')
          EXPIRED = new('expired')
          SUCCESSFUL = new('successful')
        end
      end
    end
  end
end
