# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Moov
  module Models
    module Components

      class BusinessPresence < T::Enum


        enums do
          COMMERCIAL_OFFICE = new('commercial-office')
          HOME_BASED = new('home-based')
          MIXED_PRESENCE = new('mixed-presence')
          MOBILE_BUSINESS = new('mobile-business')
          ONLINE_ONLY = new('online-only')
          RETAIL_STOREFRONT = new('retail-storefront')
        end
      end
    end
  end
end
