# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Moov
  module Models
    module Components
      # CallToAction - The text to be displayed on web form's submit button.
      # 
      # If set to "auto" the UI will automatically select between 
      # "pay" and "confirm" for payments and payouts respectively.
      class CallToAction < T::Enum


        enums do
          PAY = new('pay')
          BOOK = new('book')
          SUBSCRIBE = new('subscribe')
          DONATE = new('donate')
          CONFIRM = new('confirm')
          AUTO = new('auto')
        end
      end
    end
  end
end
