# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Moov
  module Models
    module Components
      # Details of a capture against an authorization.
      class Capture
        extend T::Sig
        include Crystalline::MetadataFields

        # Identifier for the capture.
        field :capture_id, ::String, { 'format_json': { 'letter_case': ::Moov::Utils.field_name('captureID'), required: true } }

        field :amount, Models::Components::AmountDecimal, { 'format_json': { 'letter_case': ::Moov::Utils.field_name('amount'), required: true } }
        # Indicates whether this is intended to be the final capture.
        field :is_final, Crystalline::Boolean.new, { 'format_json': { 'letter_case': ::Moov::Utils.field_name('isFinal'), required: true } }

        field :status, Models::Components::CaptureStatus, { 'format_json': { 'letter_case': ::Moov::Utils.field_name('status'), required: true, 'decoder': ::Moov::Utils.open_enum_from_string(Models::Components::CaptureStatus, false) } }

        field :created_on, ::DateTime, { 'format_json': { 'letter_case': ::Moov::Utils.field_name('createdOn'), required: true, 'decoder': ::Moov::Utils.datetime_from_iso_format(false) } }
        # Payment method of the merchant account the funds were captured into. For card-acquiring transfers, this must be a moov-wallet payment method.
        field :destination_payment_method_id, ::String, { 'format_json': { 'letter_case': ::Moov::Utils.field_name('destinationPaymentMethodID'), required: true } }
        # An optional description of the capture that is used on receipts and for your own internal use.
        field :description, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Moov::Utils.field_name('description') } }
        # Free-form key-value pair list. Useful for storing information that is not captured elsewhere.
        field :metadata, Crystalline::Nilable.new(Crystalline::Hash.new(Symbol, ::String)), { 'format_json': { 'letter_case': ::Moov::Utils.field_name('metadata') } }
        # Optional alias from a foreign/external system which can be used to reference this resource.
        field :foreign_id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Moov::Utils.field_name('foreignID') } }
        # An optional collection of line items for a transfer.
        # When line items are provided, their total plus tax must equal the transfer amount.
        field :line_items, Crystalline::Nilable.new(Models::Components::TransferLineItems), { 'format_json': { 'letter_case': ::Moov::Utils.field_name('lineItems') } }

        field :amount_details, Crystalline::Nilable.new(Models::Components::TransferAmountDetails), { 'format_json': { 'letter_case': ::Moov::Utils.field_name('amountDetails') } }
        # The facilitator fee applied to this capture.
        # The transfer's facilitator fee is the sum of its capture fees.
        field :facilitator_fee_amount, Crystalline::Nilable.new(Models::Components::AmountDecimal), { 'format_json': { 'letter_case': ::Moov::Utils.field_name('facilitatorFeeAmount') } }

        field :failure_code, Crystalline::Nilable.new(Models::Components::CardTransactionFailureCode), { 'format_json': { 'letter_case': ::Moov::Utils.field_name('failureCode'), 'decoder': ::Moov::Utils.open_enum_from_string(Models::Components::CardTransactionFailureCode, true) } }

        sig { params(capture_id: ::String, amount: Models::Components::AmountDecimal, is_final: T::Boolean, status: Models::Components::CaptureStatus, created_on: ::DateTime, destination_payment_method_id: ::String, description: T.nilable(::String), metadata: T.nilable(T::Hash[Symbol, ::String]), foreign_id: T.nilable(::String), line_items: T.nilable(Models::Components::TransferLineItems), amount_details: T.nilable(Models::Components::TransferAmountDetails), facilitator_fee_amount: T.nilable(Models::Components::AmountDecimal), failure_code: T.nilable(Models::Components::CardTransactionFailureCode)).void }
        def initialize(capture_id:, amount:, is_final:, status:, created_on:, destination_payment_method_id:, description: nil, metadata: nil, foreign_id: nil, line_items: nil, amount_details: nil, facilitator_fee_amount: nil, failure_code: nil)
          @capture_id = capture_id
          @amount = amount
          @is_final = is_final
          @status = status
          @created_on = created_on
          @destination_payment_method_id = destination_payment_method_id
          @description = description
          @metadata = metadata
          @foreign_id = foreign_id
          @line_items = line_items
          @amount_details = amount_details
          @facilitator_fee_amount = facilitator_fee_amount
          @failure_code = failure_code
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @capture_id == other.capture_id
          return false unless @amount == other.amount
          return false unless @is_final == other.is_final
          return false unless @status == other.status
          return false unless @created_on == other.created_on
          return false unless @destination_payment_method_id == other.destination_payment_method_id
          return false unless @description == other.description
          return false unless @metadata == other.metadata
          return false unless @foreign_id == other.foreign_id
          return false unless @line_items == other.line_items
          return false unless @amount_details == other.amount_details
          return false unless @facilitator_fee_amount == other.facilitator_fee_amount
          return false unless @failure_code == other.failure_code
          true
        end
      end
    end
  end
end
