# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Moov
  module Models
    module Components

      class CardPresentPaymentPaymentMethodPaymentMethodType < T::Enum


        enums do
          CARD_PRESENT_PAYMENT = new('card-present-payment')
        end
      end
    end
  end
end
