# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Moov
  module Models
    module Components
      # CardVerificationResult - The result of a card verification check.
      class CardVerificationResult
        include ::Crystalline::Enum
        enums do
          NO_MATCH = new('noMatch')
          MATCH = new('match')
          NOT_CHECKED = new('notChecked')
          UNAVAILABLE = new('unavailable')
          PARTIAL_MATCH = new('partialMatch')
        end
        open!
      end
    end
  end
end
