# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Moov
  module Models
    module Components
    

      class CardPayment
        extend T::Sig
        include Crystalline::MetadataFields


        field :statement_descriptor, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Moov::Utils.field_name('statementDescriptor') } }

        sig { params(statement_descriptor: T.nilable(::String)).void }
        def initialize(statement_descriptor: nil)
          @statement_descriptor = statement_descriptor
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @statement_descriptor == other.statement_descriptor
          true
        end
      end
    end
  end
end
