# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Moov
  module Models
    module Components
      # Specifies a partial amount to refund. 
      #
      # This request body is optional, an empty body will issue a refund for the full amount of the original transfer.
      class CreateRefund
        extend T::Sig
        include Crystalline::MetadataFields

        # Amount to refund in cents. If null, the original transfer's full amount will be refunded.
        field :amount, Crystalline::Nilable.new(::Integer), { 'format_json': { 'letter_case': ::Moov::Utils.field_name('amount') } }

        sig { params(amount: T.nilable(::Integer)).void }
        def initialize(amount: nil)
          @amount = amount
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @amount == other.amount
          true
        end
      end
    end
  end
end
