# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Moov
  module Models
    module Components
    
      # Request body for creating a new webhook.
      class CreateWebhook
        extend T::Sig
        include Crystalline::MetadataFields

        # The URL where webhook events will be sent.
        field :url, ::String, { 'format_json': { 'letter_case': ::Moov::Utils.field_name('url'), required: true } }
        # The status of the webhook.
        field :status, Models::Components::WebhookStatus, { 'format_json': { 'letter_case': ::Moov::Utils.field_name('status'), required: true, 'decoder': Utils.enum_from_string(Models::Components::WebhookStatus, false) } }
        # The list of event types this webhook should subscribe to.
        field :event_types, Crystalline::Array.new(Models::Components::WebhookEventType), { 'format_json': { 'letter_case': ::Moov::Utils.field_name('eventTypes'), required: true } }
        # A description of the webhook for reference. Can be an empty string.
        field :description, ::String, { 'format_json': { 'letter_case': ::Moov::Utils.field_name('description'), required: true } }

        sig { params(url: ::String, status: Models::Components::WebhookStatus, event_types: T::Array[Models::Components::WebhookEventType], description: ::String).void }
        def initialize(url:, status:, event_types:, description:)
          @url = url
          @status = status
          @event_types = event_types
          @description = description
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @url == other.url
          return false unless @status == other.status
          return false unless @event_types == other.event_types
          return false unless @description == other.description
          true
        end
      end
    end
  end
end
