# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Moov
  module Models
    module Components
    

      class CreateIndividualError
        extend T::Sig
        include Crystalline::MetadataFields


        field :name, Crystalline::Nilable.new(Models::Components::IndividualNameError), { 'format_json': { 'letter_case': ::Moov::Utils.field_name('name') } }

        field :phone, Crystalline::Nilable.new(Models::Components::PhoneNumberError), { 'format_json': { 'letter_case': ::Moov::Utils.field_name('phone') } }

        field :email, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Moov::Utils.field_name('email') } }

        field :address, Crystalline::Nilable.new(Models::Components::AddressError), { 'format_json': { 'letter_case': ::Moov::Utils.field_name('address') } }

        field :birth_date, Crystalline::Nilable.new(Models::Components::BirthDateError), { 'format_json': { 'letter_case': ::Moov::Utils.field_name('birthDate') } }

        field :government_id, Crystalline::Nilable.new(Models::Components::CreateIndividualErrorGovernmentID), { 'format_json': { 'letter_case': ::Moov::Utils.field_name('governmentID') } }

        sig { params(name: T.nilable(Models::Components::IndividualNameError), phone: T.nilable(Models::Components::PhoneNumberError), email: T.nilable(::String), address: T.nilable(Models::Components::AddressError), birth_date: T.nilable(Models::Components::BirthDateError), government_id: T.nilable(Models::Components::CreateIndividualErrorGovernmentID)).void }
        def initialize(name: nil, phone: nil, email: nil, address: nil, birth_date: nil, government_id: nil)
          @name = name
          @phone = phone
          @email = email
          @address = address
          @birth_date = birth_date
          @government_id = government_id
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @name == other.name
          return false unless @phone == other.phone
          return false unless @email == other.email
          return false unless @address == other.address
          return false unless @birth_date == other.birth_date
          return false unless @government_id == other.government_id
          true
        end
      end
    end
  end
end
