# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Moov
  module Models
    module Components

      class CreatePaymentLinkAmountDetailsValidationError
        extend T::Sig
        include Crystalline::MetadataFields


        field :tax, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Moov::Utils.field_name('tax') } }

        field :surcharge, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Moov::Utils.field_name('surcharge') } }

        sig { params(tax: T.nilable(::String), surcharge: T.nilable(::String)).void }
        def initialize(tax: nil, surcharge: nil)
          @tax = tax
          @surcharge = surcharge
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @tax == other.tax
          return false unless @surcharge == other.surcharge
          true
        end
      end
    end
  end
end
