# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Moov
  module Models
    module Components
      # An image to associate with a line item.
      class CreateInvoiceLineItemImage
        extend T::Sig
        include Crystalline::MetadataFields

        # A unique identifier for a Moov resource. Supports UUID format (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx) or typed format with base32-encoded UUID and type suffix (e.g., kuoaydiojf7uszaokc2ggnaaaa_xfer).
        field :image_id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Moov::Utils.field_name('imageID') } }

        sig { params(image_id: T.nilable(::String)).void }
        def initialize(image_id: nil)
          @image_id = image_id
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @image_id == other.image_id
          true
        end
      end
    end
  end
end
