# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Moov
  module Models
    module Components
      # Represents a single item in a scheduled transfer, including optional modifiers and quantity.
      class CreateScheduledTransferLineItem
        extend T::Sig
        include Crystalline::MetadataFields

        # The name of the item.
        field :name, ::String, { 'format_json': { 'letter_case': ::Moov::Utils.field_name('name'), required: true } }
        # The base price of the item before applying option modifiers.
        field :base_price, Models::Components::AmountDecimal, { 'format_json': { 'letter_case': ::Moov::Utils.field_name('basePrice'), required: true } }
        # The quantity of this item.
        field :quantity, ::Integer, { 'format_json': { 'letter_case': ::Moov::Utils.field_name('quantity'), required: true } }
        # Optional list of modifiers applied to this item (e.g., toppings, upgrades, customizations).
        field :options, Crystalline::Nilable.new(Crystalline::Array.new(Models::Components::CreateScheduledTransferLineItemOption)), { 'format_json': { 'letter_case': ::Moov::Utils.field_name('options') } }
        #   Optional unique identifier associating the line item with a product.
        #   This is for reporting or tracking purposes, and does not populate other details of the line item.
        field :product_id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Moov::Utils.field_name('productID') } }
        #   Optional list of images associated with this line item.
        #   This field is being deprecated in favor using the images associated with a productID and will soon be unsupported.
        #
        # @deprecated true: This will be removed in a future release, please migrate away from it as soon as possible.
        field :image_i_ds, Crystalline::Nilable.new(Crystalline::Array.new(::String)), { 'format_json': { 'letter_case': ::Moov::Utils.field_name('imageIDs') } }

        sig { params(name: ::String, base_price: Models::Components::AmountDecimal, quantity: ::Integer, options: T.nilable(T::Array[Models::Components::CreateScheduledTransferLineItemOption]), product_id: T.nilable(::String), image_i_ds: T.nilable(T::Array[::String])).void }
        def initialize(name:, base_price:, quantity:, options: nil, product_id: nil, image_i_ds: nil)
          @name = name
          @base_price = base_price
          @quantity = quantity
          @options = options
          @product_id = product_id
          @image_i_ds = image_i_ds
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @name == other.name
          return false unless @base_price == other.base_price
          return false unless @quantity == other.quantity
          return false unless @options == other.options
          return false unless @product_id == other.product_id
          return false unless @image_i_ds == other.image_i_ds
          true
        end
      end
    end
  end
end
