# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Moov
  module Models
    module Components

      class CreateCancellation
        extend T::Sig
        include Crystalline::MetadataFields


        field :amount, Crystalline::Nilable.new(Models::Components::AmountDecimal), { 'format_json': { 'letter_case': ::Moov::Utils.field_name('amount') } }

        sig { params(amount: T.nilable(Models::Components::AmountDecimal)).void }
        def initialize(amount: nil)
          @amount = amount
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @amount == other.amount
          true
        end
      end
    end
  end
end
