# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Moov
  module Models
    module Components

      class CreateReversal
        extend T::Sig
        include Crystalline::MetadataFields

        # Amount to reverse.
        # Before v2026.10, specify the amount in integer cents.
        # For supported auth-capture `card-payment` reversals in v2026.10 and later, a transfer with no captures uses the full `capturableAmount`.
        # For those transfers with one final capture, a cancellation uses the full capture amount, while a refund may be partial.
        field :amount, ::Integer, { 'format_json': { 'letter_case': ::Moov::Utils.field_name('amount'), required: true } }

        sig { params(amount: ::Integer).void }
        def initialize(amount:)
          @amount = amount
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @amount == other.amount
          true
        end
      end
    end
  end
end
