# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Moov
  module Models
    module Components
    
      # An optional collection of line items for a payment link.
      # When line items are provided, their total plus sales tax must equal the payment link amount.
      class CreatePaymentLinkLineItemsUpdate
        extend T::Sig
        include Crystalline::MetadataFields

        # The list of line items.
        field :items, Crystalline::Nilable.new(Crystalline::Array.new(Models::Components::CreatePaymentLinkLineItem)), { 'format_json': { 'letter_case': ::Moov::Utils.field_name('items') } }

        sig { params(items: T.nilable(T::Array[Models::Components::CreatePaymentLinkLineItem])).void }
        def initialize(items: nil)
          @items = items
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @items == other.items
          true
        end
      end
    end
  end
end
