# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Moov
  module Models
    module Components
      # DomesticPushToCard - Indicates which level of domestic push-to-card transfer is supported by the card, if any.
      class DomesticPushToCard < T::Enum


        enums do
          NOT_SUPPORTED = new('not-supported')
          STANDARD = new('standard')
          FAST_FUNDS = new('fast-funds')
          UNKNOWN = new('unknown')
        end
      end
    end
  end
end
