# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Moov
  module Models
    module Components

      class EnrichedBusinessProfile
        extend T::Sig
        include Crystalline::MetadataFields


        field :address, Crystalline::Nilable.new(Models::Components::Address), { 'format_json': { 'letter_case': ::Moov::Utils.field_name('address') } }

        field :email, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Moov::Utils.field_name('email') } }

        field :industry_codes, Crystalline::Nilable.new(Models::Components::EnrichedIndustryCodes), { 'format_json': { 'letter_case': ::Moov::Utils.field_name('industryCodes') } }

        field :legal_business_name, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Moov::Utils.field_name('legalBusinessName') } }

        field :phone, Crystalline::Nilable.new(Models::Components::PhoneNumber), { 'format_json': { 'letter_case': ::Moov::Utils.field_name('phone') } }

        field :website, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Moov::Utils.field_name('website') } }

        sig { params(address: T.nilable(Models::Components::Address), email: T.nilable(::String), industry_codes: T.nilable(Models::Components::EnrichedIndustryCodes), legal_business_name: T.nilable(::String), phone: T.nilable(Models::Components::PhoneNumber), website: T.nilable(::String)).void }
        def initialize(address: nil, email: nil, industry_codes: nil, legal_business_name: nil, phone: nil, website: nil)
          @address = address
          @email = email
          @industry_codes = industry_codes
          @legal_business_name = legal_business_name
          @phone = phone
          @website = website
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @address == other.address
          return false unless @email == other.email
          return false unless @industry_codes == other.industry_codes
          return false unless @legal_business_name == other.legal_business_name
          return false unless @phone == other.phone
          return false unless @website == other.website
          true
        end
      end
    end
  end
end
