# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Moov
  module Models
    module Components
      # An industry's MCC/SIC/NAICS codes, along with descriptive title.
      class EnrichedIndustry
        extend T::Sig
        include Crystalline::MetadataFields


        field :title, ::String, { 'format_json': { 'letter_case': ::Moov::Utils.field_name('title'), required: true } }
        # North American Industry Classification System
        field :naics, ::String, { 'format_json': { 'letter_case': ::Moov::Utils.field_name('naics'), required: true } }
        # Standard Industrial Classification
        field :sic, ::String, { 'format_json': { 'letter_case': ::Moov::Utils.field_name('sic'), required: true } }
        # Merchant Category Code
        field :mcc, ::String, { 'format_json': { 'letter_case': ::Moov::Utils.field_name('mcc'), required: true } }

        sig { params(title: ::String, naics: ::String, sic: ::String, mcc: ::String).void }
        def initialize(title:, naics:, sic:, mcc:)
          @title = title
          @naics = naics
          @sic = sic
          @mcc = mcc
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @title == other.title
          return false unless @naics == other.naics
          return false unless @sic == other.sic
          return false unless @mcc == other.mcc
          true
        end
      end
    end
  end
end
