# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Moov
  module Models
    module Components

      class EvidenceType < T::Enum


        enums do
          RECEIPT = new('receipt')
          PROOF_OF_DELIVERY = new('proof-of-delivery')
          CANCELATION_POLICY = new('cancelation-policy')
          TERMS_OF_SERVICE = new('terms-of-service')
          CUSTOMER_COMMUNICATION = new('customer-communication')
          GENERIC_EVIDENCE = new('generic-evidence')
          COVER_LETTER = new('cover-letter')
          OTHER = new('other')
        end
      end
    end
  end
end
