# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Moov
  module Models
    module Components

      class FeePlanAgreementStatus
        include ::Crystalline::Enum
        enums do
          ACTIVE = new('active')
          TERMINATED = new('terminated')
        end
        open!
      end
    end
  end
end
