# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Moov
  module Models
    module Components
      # FileStatus - The file's status.
      class FileStatus
        include ::Crystalline::Enum
        enums do
          PENDING = new('pending')
          APPROVED = new('approved')
          REJECTED = new('rejected')
        end
        open!
      end
    end
  end
end
