# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Moov
  module Models
    module Components
    

      class FulfillmentError
        extend T::Sig
        include Crystalline::MetadataFields


        field :method, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Moov::Utils.field_name('method') } }

        field :timeframe, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Moov::Utils.field_name('timeframe') } }

        sig { params(method: T.nilable(::String), timeframe: T.nilable(::String)).void }
        def initialize(method: nil, timeframe: nil)
          @method = method
          @timeframe = timeframe
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @method == other.method
          return false unless @timeframe == other.timeframe
          true
        end
      end
    end
  end
end
