# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Moov
  module Models
    module Components
    

      class GeneratedByTransferID
        extend T::Sig
        include Crystalline::MetadataFields


        field :transfer_id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Moov::Utils.field_name('transferID') } }

        sig { params(transfer_id: T.nilable(::String)).void }
        def initialize(transfer_id: nil)
          @transfer_id = transfer_id
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @transfer_id == other.transfer_id
          true
        end
      end
    end
  end
end
