# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Moov
  module Models
    module Components
      #   The `paymentMethodData` object from Google Pay's
      #   [PaymentData](https://developers.google.com/pay/api/web/reference/response-objects#PaymentData) response.
      class GooglePayPaymentMethodData
        extend T::Sig
        include Crystalline::MetadataFields

        #   Unencrypted card metadata from
        #   [CardInfo](https://developers.google.com/pay/api/web/reference/response-objects#CardInfo).
        field :info, Models::Components::GooglePayCardInfo, { 'format_json': { 'letter_case': ::Moov::Utils.field_name('info'), required: true } }
        #   Contains the encrypted payment token from Google Pay.
        #
        #   The `token` field is a JSON-encoded string containing the ECv2 encrypted payment token.
        field :tokenization_data, Models::Components::GooglePayTokenizationData, { 'format_json': { 'letter_case': ::Moov::Utils.field_name('tokenizationData'), required: true } }
        # The type of payment method. Always `CARD`.
        field :type, Crystalline::Nilable.new(Models::Components::GooglePayPaymentMethodDataType), { 'format_json': { 'letter_case': ::Moov::Utils.field_name('type'), 'decoder': ::Moov::Utils.enum_from_string(Models::Components::GooglePayPaymentMethodDataType, true) } }
        # A user-facing description of the payment method.
        field :description, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Moov::Utils.field_name('description') } }

        sig { params(info: Models::Components::GooglePayCardInfo, tokenization_data: Models::Components::GooglePayTokenizationData, type: T.nilable(Models::Components::GooglePayPaymentMethodDataType), description: T.nilable(::String)).void }
        def initialize(info:, tokenization_data:, type: nil, description: nil)
          @info = info
          @tokenization_data = tokenization_data
          @type = type
          @description = description
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @info == other.info
          return false unless @tokenization_data == other.tokenization_data
          return false unless @type == other.type
          return false unless @description == other.description
          true
        end
      end
    end
  end
end
