# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Moov
  module Models
    module Components
      #   Unencrypted card metadata from
      #   [CardInfo](https://developers.google.com/pay/api/web/reference/response-objects#CardInfo).
      class GooglePayCardInfo
        extend T::Sig
        include Crystalline::MetadataFields

        # The card network. One of AMEX, DISCOVER, INTERAC, JCB, MASTERCARD, VISA, or OTHER.
        field :card_network, Models::Components::CardNetwork, { 'format_json': { 'letter_case': ::Moov::Utils.field_name('cardNetwork'), required: true, 'decoder': ::Moov::Utils.enum_from_string(Models::Components::CardNetwork, false) } }
        # The last four digits of the card number.
        field :card_details, ::String, { 'format_json': { 'letter_case': ::Moov::Utils.field_name('cardDetails'), required: true } }
        # The funding source of the card. One of CREDIT, DEBIT, PREPAID, or UNKNOWN.
        field :card_funding_source, Crystalline::Nilable.new(Models::Components::CardFundingSource), { 'format_json': { 'letter_case': ::Moov::Utils.field_name('cardFundingSource'), 'decoder': ::Moov::Utils.enum_from_string(Models::Components::CardFundingSource, true) } }
        #   Billing address as returned by Google Pay.
        #
        #   Refer to [Google's documentation](https://developers.google.com/pay/api/web/reference/response-objects#Address)
        #   for more information.
        field :billing_address, Crystalline::Nilable.new(Models::Components::GooglePayBillingAddress), { 'format_json': { 'letter_case': ::Moov::Utils.field_name('billingAddress') } }
        # 3-D Secure assurance details from Google Pay.
        field :assurance_details, Crystalline::Nilable.new(Models::Components::GooglePayAssuranceDetails), { 'format_json': { 'letter_case': ::Moov::Utils.field_name('assuranceDetails') } }

        sig { params(card_network: Models::Components::CardNetwork, card_details: ::String, card_funding_source: T.nilable(Models::Components::CardFundingSource), billing_address: T.nilable(Models::Components::GooglePayBillingAddress), assurance_details: T.nilable(Models::Components::GooglePayAssuranceDetails)).void }
        def initialize(card_network:, card_details:, card_funding_source: nil, billing_address: nil, assurance_details: nil)
          @card_network = card_network
          @card_details = card_details
          @card_funding_source = card_funding_source
          @billing_address = billing_address
          @assurance_details = assurance_details
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @card_network == other.card_network
          return false unless @card_details == other.card_details
          return false unless @card_funding_source == other.card_funding_source
          return false unless @billing_address == other.billing_address
          return false unless @assurance_details == other.assurance_details
          true
        end
      end
    end
  end
end
