# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Moov
  module Models
    module Components
      # InstantBankNetwork - The network that the transaction was processed on.
      class InstantBankNetwork
        include ::Crystalline::Enum
        enums do
          FEDNOW = new('fednow')
          RTP = new('rtp')
        end
        open!
      end
    end
  end
end
