# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Moov
  module Models
    module Components

      class InstantBankCreditTransferProcessingDetails
        extend T::Sig
        include Crystalline::MetadataFields

        # The network that the transaction was processed on.
        field :network, Models::Components::InstantBankNetwork, { 'format_json': { 'letter_case': ::Moov::Utils.field_name('network'), required: true, 'decoder': ::Moov::Utils.enum_from_string(Models::Components::InstantBankNetwork, false) } }

        field :network_response_code, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Moov::Utils.field_name('networkResponseCode') } }
        # Status codes for instant-bank failures.
        field :failure_code, Crystalline::Nilable.new(Models::Components::InstantBankFailureCode), { 'format_json': { 'letter_case': ::Moov::Utils.field_name('failureCode'), 'decoder': ::Moov::Utils.enum_from_string(Models::Components::InstantBankFailureCode, true) } }

        field :end_to_end_id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Moov::Utils.field_name('endToEndID') } }

        sig { params(network: Models::Components::InstantBankNetwork, network_response_code: T.nilable(::String), failure_code: T.nilable(Models::Components::InstantBankFailureCode), end_to_end_id: T.nilable(::String)).void }
        def initialize(network:, network_response_code: nil, failure_code: nil, end_to_end_id: nil)
          @network = network
          @network_response_code = network_response_code
          @failure_code = failure_code
          @end_to_end_id = end_to_end_id
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @network == other.network
          return false unless @network_response_code == other.network_response_code
          return false unless @failure_code == other.failure_code
          return false unless @end_to_end_id == other.end_to_end_id
          true
        end
      end
    end
  end
end
