# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Moov
  module Models
    module Components
    

      class Invoice
        extend T::Sig
        include Crystalline::MetadataFields


        field :invoice_id, ::String, { 'format_json': { 'letter_case': ::Moov::Utils.field_name('invoiceID'), required: true } }

        field :invoice_number, ::String, { 'format_json': { 'letter_case': ::Moov::Utils.field_name('invoiceNumber'), required: true } }

        field :customer_account_id, ::String, { 'format_json': { 'letter_case': ::Moov::Utils.field_name('customerAccountID'), required: true } }

        field :partner_account_id, ::String, { 'format_json': { 'letter_case': ::Moov::Utils.field_name('partnerAccountID'), required: true } }

        field :status, Models::Components::InvoiceStatus, { 'format_json': { 'letter_case': ::Moov::Utils.field_name('status'), required: true, 'decoder': Utils.enum_from_string(Models::Components::InvoiceStatus, false) } }
        # A collection of line items for an invoice.
        field :line_items, Models::Components::InvoiceLineItems, { 'format_json': { 'letter_case': ::Moov::Utils.field_name('lineItems'), required: true } }

        field :subtotal_amount, Models::Components::AmountDecimal, { 'format_json': { 'letter_case': ::Moov::Utils.field_name('subtotalAmount'), required: true } }

        field :tax_amount, Models::Components::AmountDecimal, { 'format_json': { 'letter_case': ::Moov::Utils.field_name('taxAmount'), required: true } }
        # Total amount of the invoice, sum of subTotalAmount and taxAmount
        field :total_amount, Models::Components::AmountDecimal, { 'format_json': { 'letter_case': ::Moov::Utils.field_name('totalAmount'), required: true } }
        # Total amount of pending transfers paid towards the invoice
        field :pending_amount, Models::Components::AmountDecimal, { 'format_json': { 'letter_case': ::Moov::Utils.field_name('pendingAmount'), required: true } }
        # Total amount of completed transfers paid towards the invoice
        field :paid_amount, Models::Components::AmountDecimal, { 'format_json': { 'letter_case': ::Moov::Utils.field_name('paidAmount'), required: true } }
        # Total amount of refunds initiated against transfers paid towards the invoice
        field :refunded_amount, Models::Components::AmountDecimal, { 'format_json': { 'letter_case': ::Moov::Utils.field_name('refundedAmount'), required: true } }
        # Total amount of disputes initiated against transfers paid towards the invoice
        field :disputed_amount, Models::Components::AmountDecimal, { 'format_json': { 'letter_case': ::Moov::Utils.field_name('disputedAmount'), required: true } }

        field :created_on, ::DateTime, { 'format_json': { 'letter_case': ::Moov::Utils.field_name('createdOn'), required: true, 'decoder': Utils.datetime_from_iso_format(false) } }

        field :description, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Moov::Utils.field_name('description') } }

        field :payment_link_code, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Moov::Utils.field_name('paymentLinkCode') } }
        # Payment made towards an invoice, will be either a transfer or an external payment.
        field :invoice_payments, Crystalline::Nilable.new(Crystalline::Array.new(Models::Components::InvoicePayment)), { 'format_json': { 'letter_case': ::Moov::Utils.field_name('invoicePayments') } }

        field :invoice_date, Crystalline::Nilable.new(::DateTime), { 'format_json': { 'letter_case': ::Moov::Utils.field_name('invoiceDate'), 'decoder': Utils.datetime_from_iso_format(true) } }

        field :due_date, Crystalline::Nilable.new(::DateTime), { 'format_json': { 'letter_case': ::Moov::Utils.field_name('dueDate'), 'decoder': Utils.datetime_from_iso_format(true) } }

        field :sent_on, Crystalline::Nilable.new(::DateTime), { 'format_json': { 'letter_case': ::Moov::Utils.field_name('sentOn'), 'decoder': Utils.datetime_from_iso_format(true) } }

        field :paid_on, Crystalline::Nilable.new(::DateTime), { 'format_json': { 'letter_case': ::Moov::Utils.field_name('paidOn'), 'decoder': Utils.datetime_from_iso_format(true) } }

        field :canceled_on, Crystalline::Nilable.new(::DateTime), { 'format_json': { 'letter_case': ::Moov::Utils.field_name('canceledOn'), 'decoder': Utils.datetime_from_iso_format(true) } }

        sig { params(invoice_id: ::String, invoice_number: ::String, customer_account_id: ::String, partner_account_id: ::String, status: Models::Components::InvoiceStatus, line_items: Models::Components::InvoiceLineItems, subtotal_amount: Models::Components::AmountDecimal, tax_amount: Models::Components::AmountDecimal, total_amount: Models::Components::AmountDecimal, pending_amount: Models::Components::AmountDecimal, paid_amount: Models::Components::AmountDecimal, refunded_amount: Models::Components::AmountDecimal, disputed_amount: Models::Components::AmountDecimal, created_on: ::DateTime, description: T.nilable(::String), payment_link_code: T.nilable(::String), invoice_payments: T.nilable(T::Array[Models::Components::InvoicePayment]), invoice_date: T.nilable(::DateTime), due_date: T.nilable(::DateTime), sent_on: T.nilable(::DateTime), paid_on: T.nilable(::DateTime), canceled_on: T.nilable(::DateTime)).void }
        def initialize(invoice_id:, invoice_number:, customer_account_id:, partner_account_id:, status:, line_items:, subtotal_amount:, tax_amount:, total_amount:, pending_amount:, paid_amount:, refunded_amount:, disputed_amount:, created_on:, description: nil, payment_link_code: nil, invoice_payments: nil, invoice_date: nil, due_date: nil, sent_on: nil, paid_on: nil, canceled_on: nil)
          @invoice_id = invoice_id
          @invoice_number = invoice_number
          @customer_account_id = customer_account_id
          @partner_account_id = partner_account_id
          @status = status
          @line_items = line_items
          @subtotal_amount = subtotal_amount
          @tax_amount = tax_amount
          @total_amount = total_amount
          @pending_amount = pending_amount
          @paid_amount = paid_amount
          @refunded_amount = refunded_amount
          @disputed_amount = disputed_amount
          @created_on = created_on
          @description = description
          @payment_link_code = payment_link_code
          @invoice_payments = invoice_payments
          @invoice_date = invoice_date
          @due_date = due_date
          @sent_on = sent_on
          @paid_on = paid_on
          @canceled_on = canceled_on
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @invoice_id == other.invoice_id
          return false unless @invoice_number == other.invoice_number
          return false unless @customer_account_id == other.customer_account_id
          return false unless @partner_account_id == other.partner_account_id
          return false unless @status == other.status
          return false unless @line_items == other.line_items
          return false unless @subtotal_amount == other.subtotal_amount
          return false unless @tax_amount == other.tax_amount
          return false unless @total_amount == other.total_amount
          return false unless @pending_amount == other.pending_amount
          return false unless @paid_amount == other.paid_amount
          return false unless @refunded_amount == other.refunded_amount
          return false unless @disputed_amount == other.disputed_amount
          return false unless @created_on == other.created_on
          return false unless @description == other.description
          return false unless @payment_link_code == other.payment_link_code
          return false unless @invoice_payments == other.invoice_payments
          return false unless @invoice_date == other.invoice_date
          return false unless @due_date == other.due_date
          return false unless @sent_on == other.sent_on
          return false unless @paid_on == other.paid_on
          return false unless @canceled_on == other.canceled_on
          true
        end
      end
    end
  end
end
