# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Moov
  module Models
    module Components
    

      class InvoiceExternalPaymentPaymentType < T::Enum


        enums do
          EXTERNAL = new('external')
        end
      end
    end
  end
end
