# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Moov
  module Models
    module Components

      class InvoicePaymentType
        include ::Crystalline::Enum
        enums do
          TRANSFER = new('transfer')
          EXTERNAL = new('external')
        end
        open!
      end
    end
  end
end
