# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Moov
  module Models
    module Components
      # IssuedCardFormFactor - Specifies the type of spend card to be issued. Presently supports virtual only, providing a digital number without a physical card.
      class IssuedCardFormFactor < T::Enum
        enums do
          VIRTUAL = new('virtual')
        end
      end
    end
  end
end
