# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Moov
  module Models
    module Components

      class IssuingVelocityLimitError
        extend T::Sig
        include Crystalline::MetadataFields


        field :amount, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Moov::Utils.field_name('amount') } }

        field :count, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Moov::Utils.field_name('count') } }

        field :interval, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Moov::Utils.field_name('interval') } }

        sig { params(amount: T.nilable(::String), count: T.nilable(::String), interval: T.nilable(::String)).void }
        def initialize(amount: nil, count: nil, interval: nil)
          @amount = amount
          @count = count
          @interval = interval
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @amount == other.amount
          return false unless @count == other.count
          return false unless @interval == other.interval
          true
        end
      end
    end
  end
end
