# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Moov
  module Models
    module Components
      # Kind - The type of receipt being requested.
      class Kind < T::Enum
        enums do
          SALE_CUSTOMER_V1 = new('sale.customer.v1')
        end
      end
    end
  end
end
