# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Moov
  module Models
    module Components
      # The predefined merchant category groups available for issued card spend controls.
      class MerchantCategories
        extend T::Sig
        include Crystalline::MetadataFields


        field :merchant_categories, Crystalline::Array.new(Models::Components::MerchantCategory), { 'format_json': { 'letter_case': ::Moov::Utils.field_name('merchantCategories'), required: true } }

        sig { params(merchant_categories: T::Array[Models::Components::MerchantCategory]).void }
        def initialize(merchant_categories:)
          @merchant_categories = merchant_categories
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @merchant_categories == other.merchant_categories
          true
        end
      end
    end
  end
end
