# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Moov
  module Models
    module Components
      # Restricts card usage by merchant category.
      class MerchantCategoryRestrictions
        extend T::Sig
        include Crystalline::MetadataFields

        # Whether the listed categories are the only ones allowed, or the ones to block.
        field :mode, Models::Components::IssuingControlsRestrictionMode, { 'format_json': { 'letter_case': ::Moov::Utils.field_name('mode'), required: true, 'decoder': ::Moov::Utils.enum_from_string(Models::Components::IssuingControlsRestrictionMode, false) } }
        # Predefined category groups to allow or block.
        field :categories, Crystalline::Nilable.new(Crystalline::Array.new(Models::Components::IssuingMerchantCategory)), { 'format_json': { 'letter_case': ::Moov::Utils.field_name('categories') } }
        # Individual merchant category codes (MCCs) to allow or block, for codes not covered by a predefined category.
        field :custom_mc_cs, Crystalline::Nilable.new(Crystalline::Array.new(::String)), { 'format_json': { 'letter_case': ::Moov::Utils.field_name('customMCCs') } }
        # Merchants that are exempt from category restrictions regardless of their category.
        field :exempt_merchants, Crystalline::Nilable.new(Crystalline::Array.new(Models::Components::MerchantEntry)), { 'format_json': { 'letter_case': ::Moov::Utils.field_name('exemptMerchants') } }

        sig { params(mode: Models::Components::IssuingControlsRestrictionMode, categories: T.nilable(T::Array[Models::Components::IssuingMerchantCategory]), custom_mc_cs: T.nilable(T::Array[::String]), exempt_merchants: T.nilable(T::Array[Models::Components::MerchantEntry])).void }
        def initialize(mode:, categories: nil, custom_mc_cs: nil, exempt_merchants: nil)
          @mode = mode
          @categories = categories
          @custom_mc_cs = custom_mc_cs
          @exempt_merchants = exempt_merchants
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @mode == other.mode
          return false unless @categories == other.categories
          return false unless @custom_mc_cs == other.custom_mc_cs
          return false unless @exempt_merchants == other.exempt_merchants
          true
        end
      end
    end
  end
end
