# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Moov
  module Models
    module Components
      # MonthlyVolumeRange - The low value in each range is included. The high value in each range is excluded.
      class MonthlyVolumeRange < T::Enum
        enums do
          UNDER_10K = new('under-10k')
          TENK_50K = new('10k-50k')
          FIFTYK_100K = new('50k-100k')
          ONE_HUNDREDK_250K = new('100k-250k')
          TWO_HUNDRED_AND_FIFTYK_500K = new('250k-500k')
          FIVE_HUNDREDK_1M = new('500k-1m')
          ONEM_5M = new('1m-5m')
          OVER_5M = new('over-5m')
        end
      end
    end
  end
end
