# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Moov
  module Models
    module Components
      # OAuth2ClientType - The type of client requesting an OAuth2 token. Short codes are accepted as aliases for the corresponding client types.
      class OAuth2ClientType < T::Enum
        enums do
          WEB = new('web')
          DEVICE = new('device')
          SERVICE = new('service')
          W = new('w')
          D = new('d')
          S = new('s')
        end
      end
    end
  end
end
