# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Moov
  module Models
    module Components
      # Contains details on why the occurrence errored.
      class OccurrencesResponseError
        extend T::Sig
        include Crystalline::MetadataFields


        field :message, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Moov::Utils.field_name('message') } }

        sig { params(message: T.nilable(::String)).void }
        def initialize(message: nil)
          @message = message
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @message == other.message
          true
        end
      end
    end
  end
end
