# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Moov
  module Models
    module Components
      # The account that created the onboarding invite.
      class OnboardingPartnerAccount
        extend T::Sig
        include Crystalline::MetadataFields

        # The account ID of the partner that created the invite.
        field :account_id, ::String, { 'format_json': { 'letter_case': ::Moov::Utils.field_name('accountID'), required: true } }
        # The operating mode for an account.
        field :account_mode, Models::Components::Mode, { 'format_json': { 'letter_case': ::Moov::Utils.field_name('accountMode'), required: true, 'decoder': Utils.enum_from_string(Models::Components::Mode, false) } }
        # The name of the Moov account used to create the onboarding invite.
        field :display_name, ::String, { 'format_json': { 'letter_case': ::Moov::Utils.field_name('displayName'), required: true } }

        sig { params(account_id: ::String, account_mode: Models::Components::Mode, display_name: ::String).void }
        def initialize(account_id:, account_mode:, display_name:)
          @account_id = account_id
          @account_mode = account_mode
          @display_name = display_name
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @account_id == other.account_id
          return false unless @account_mode == other.account_mode
          return false unless @display_name == other.display_name
          true
        end
      end
    end
  end
end
