# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Moov
  module Models
    module Components

      class PaymentLinkAmountDetails
        extend T::Sig
        include Crystalline::MetadataFields

        # The amount of surcharge applied to the payment link.
        field :surcharge, Crystalline::Nilable.new(Models::Components::AmountDecimal), { 'format_json': { 'letter_case': ::Moov::Utils.field_name('surcharge') } }

        sig { params(surcharge: T.nilable(Models::Components::AmountDecimal)).void }
        def initialize(surcharge: nil)
          @surcharge = surcharge
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @surcharge == other.surcharge
          true
        end
      end
    end
  end
end
