# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Moov
  module Models
    module Components
      # Options for payout links used to send a payout.
      class PaymentLinkPayoutDetails
        extend T::Sig
        include Crystalline::MetadataFields

        # A list of payment methods that should be supported for this payment link.
        field :allowed_methods, Crystalline::Array.new(Models::Components::DisbursementPaymentMethodType), { 'format_json': { 'letter_case': ::Moov::Utils.field_name('allowedMethods'), required: true } }
        # Specify the intended recipient of the payout.
        # Either `email` or `phone` must be specified, but not both.
        #
        # This information will be used to authenticate the end user when they follow the payment link.
        field :recipient, Models::Components::PayoutRecipient, { 'format_json': { 'letter_case': ::Moov::Utils.field_name('recipient'), required: true } }
        # Optional free-form metadata for the transfer.
        field :metadata, Crystalline::Nilable.new(Crystalline::Hash.new(Symbol, ::String)), { 'format_json': { 'letter_case': ::Moov::Utils.field_name('metadata') } }
        # Delivery options for `push-to-card` and `push-to-apple-pay` payouts.
        field :push_options, Crystalline::Nilable.new(Models::Components::PushOptions), { 'format_json': { 'letter_case': ::Moov::Utils.field_name('pushOptions') } }
        # Indicates which party pays the fee, keyed by `PayoutFeePaidByKey`. If keys are not set,
        # the default is `source`.
        #
        # Possible `PayoutFeePaidByKey` keys: `instant-push-to-card`, `deferred-push-to-card`, `instant-push-to-apple-pay`, `deferred-push-to-apple-pay`, `instant-bank-credit` (API v2026.01.00 and later), `rtp-credit`, `ach-credit-same-day`, `ach-credit-standard`, `push-to-google-pay`
        field :fee_paid_by, Crystalline::Nilable.new(Crystalline::Hash.new(Symbol, Models::Components::FeePaidBy)), { 'format_json': { 'letter_case': ::Moov::Utils.field_name('feePaidBy') } }

        sig { params(allowed_methods: T::Array[Models::Components::DisbursementPaymentMethodType], recipient: Models::Components::PayoutRecipient, metadata: T.nilable(T::Hash[Symbol, ::String]), push_options: T.nilable(Models::Components::PushOptions), fee_paid_by: T.nilable(T::Hash[Symbol, Models::Components::FeePaidBy])).void }
        def initialize(allowed_methods:, recipient:, metadata: nil, push_options: nil, fee_paid_by: nil)
          @allowed_methods = allowed_methods
          @recipient = recipient
          @metadata = metadata
          @push_options = push_options
          @fee_paid_by = fee_paid_by
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @allowed_methods == other.allowed_methods
          return false unless @recipient == other.recipient
          return false unless @metadata == other.metadata
          return false unless @push_options == other.push_options
          return false unless @fee_paid_by == other.fee_paid_by
          true
        end
      end
    end
  end
end
