# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Moov
  module Models
    module Components

      class PaymentLinkStatus
        include ::Crystalline::Enum
        enums do
          ACTIVE = new('active')
          USED = new('used')
          DISABLED = new('disabled')
          EXPIRED = new('expired')
        end
        open!
      end
    end
  end
end
