# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Moov
  module Models
    module Components
      # PullFromCardTransactionStatus - Status of a pull-from-card transaction.
      class PullFromCardTransactionStatus
        include ::Crystalline::Enum
        enums do
          INITIATED = new('initiated')
          FAILED = new('failed')
          COMPLETED = new('completed')
        end
        open!
      end
    end
  end
end
