# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Moov
  module Models
    module Components

      class PullFromGooglePayTransferPaymentMethodPaymentMethodType < T::Enum
        enums do
          PULL_FROM_GOOGLE_PAY = new('pull-from-google-pay')
        end
      end
    end
  end
end
