# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Moov
  module Models
    module Components
      # PushDeliverySpeed - Delivery speed options for push-to-card payouts.
      class PushDeliverySpeed < T::Enum
        enums do
          INSTANT = new('instant')
          DEFERRED = new('deferred')
        end
      end
    end
  end
end
