# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Moov
  module Models
    module Components

      class RefundCardStatus < T::Enum
        enums do
          INITIATED = new('initiated')
          CONFIRMED = new('confirmed')
          SETTLED = new('settled')
          FAILED = new('failed')
          COMPLETED = new('completed')
        end
      end
    end
  end
end
