# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Moov
  module Models
    module Components

      class RefundStatus < T::Enum
        enums do
          CREATED = new('created')
          PENDING = new('pending')
          COMPLETED = new('completed')
          FAILED = new('failed')
        end
      end
    end
  end
end
