# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Moov
  module Models
    module Components

      class ReturnPolicyType < T::Enum
        enums do
          NONE = new('none')
          EXCHANGE_ONLY = new('exchangeOnly')
          WITHIN_THIRTY_DAYS = new('withinThirtyDays')
          OTHER = new('other')
        end
      end
    end
  end
end
