# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Moov
  module Models
    module Components
    

      class ReversedWithCancellation
        extend T::Sig
        include Crystalline::MetadataFields


        field :cancellation, Models::Components::Cancellation, { 'format_json': { 'letter_case': ::Moov::Utils.field_name('cancellation'), required: true } }

        sig { params(cancellation: Models::Components::Cancellation).void }
        def initialize(cancellation:)
          @cancellation = cancellation
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @cancellation == other.cancellation
          true
        end
      end
    end
  end
end
