# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Moov
  module Models
    module Components
      # RTPRejectionCode - The rejection code of an RTP transaction that caused the bank account status to change.
      # 
      # - AC03: Account Invalid
      # - AC04: Account Closed
      # - AC06: Account Blocked
      # - AC14: Creditor Account Type Invalid
      # - AG01: Transactions Forbidden On Account
      # - AG03: Transaction Type Not Supported
      # - MD07: Customer Deceased
      class RTPRejectionCode < T::Enum


        enums do
          AC03 = new('AC03')
          AC04 = new('AC04')
          AC06 = new('AC06')
          AC14 = new('AC14')
          AG01 = new('AG01')
          AG03 = new('AG03')
          MD07 = new('MD07')
        end
      end
    end
  end
end
