# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Moov
  module Models
    module Components
    
      # Describes a terminal configuration.
      class TerminalConfiguration
        extend T::Sig
        include Crystalline::MetadataFields


        field :configuration, ::String, { 'format_json': { 'letter_case': ::Moov::Utils.field_name('configuration'), required: true } }

        sig { params(configuration: ::String).void }
        def initialize(configuration:)
          @configuration = configuration
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @configuration == other.configuration
          true
        end
      end
    end
  end
end
