# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Moov
  module Models
    module Components
      # The card authorization and capture IDs associated with a transfer.
      class TransferCapture
        extend T::Sig
        include Crystalline::MetadataFields

        # ID of the card authorization associated with this transfer.
        field :authorization_id, ::String, { 'format_json': { 'letter_case': ::Moov::Utils.field_name('authorizationID'), required: true } }
        # ID of the card capture associated with this transfer.
        field :capture_id, ::String, { 'format_json': { 'letter_case': ::Moov::Utils.field_name('captureID'), required: true } }

        sig { params(authorization_id: ::String, capture_id: ::String).void }
        def initialize(authorization_id:, capture_id:)
          @authorization_id = authorization_id
          @capture_id = capture_id
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @authorization_id == other.authorization_id
          return false unless @capture_id == other.capture_id
          true
        end
      end
    end
  end
end
