# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Moov
  module Models
    module Components
    
      # TransactionSource - Specifies the nature and initiator of a transaction. 
      # 
      # Crucial for recurring and merchant-initiated transactions as per card scheme rules. 
      # Omit for customer-initiated e-commerce transactions.
      class TransactionSource < T::Enum


        enums do
          FIRST_RECURRING = new('first-recurring')
          RECURRING = new('recurring')
          UNSCHEDULED = new('unscheduled')
        end
      end
    end
  end
end
