# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Moov
  module Models
    module Components

      class TransferEventWireCreditDetails
        extend T::Sig
        include Crystalline::MetadataFields

        # Status of a transaction within the wire lifecycle.
        field :status, Models::Components::WireTransactionStatus, { 'format_json': { 'letter_case': ::Moov::Utils.field_name('status'), required: true, 'decoder': ::Moov::Utils.open_enum_from_string(Models::Components::WireTransactionStatus, false) } }
        # Status codes for wire failures.
        field :failure_code, Crystalline::Nilable.new(Models::Components::WireFailureCode), { 'format_json': { 'letter_case': ::Moov::Utils.field_name('failureCode'), 'decoder': ::Moov::Utils.open_enum_from_string(Models::Components::WireFailureCode, true) } }

        sig { params(status: Models::Components::WireTransactionStatus, failure_code: T.nilable(Models::Components::WireFailureCode)).void }
        def initialize(status:, failure_code: nil)
          @status = status
          @failure_code = failure_code
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @status == other.status
          return false unless @failure_code == other.failure_code
          true
        end
      end
    end
  end
end
