# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Moov
  module Models
    module Components
      # Indicates which party bears fees for a transfer, keyed by fee type.
      class TransferFeePaidBy
        extend T::Sig
        include Crystalline::MetadataFields

        # For payouts, indicates which party bears the fee. Defaults to `source`.
        field :payout, Crystalline::Nilable.new(Models::Components::FeePaidBy), { 'format_json': { 'letter_case': ::Moov::Utils.field_name('payout'), 'decoder': ::Moov::Utils.enum_from_string(Models::Components::FeePaidBy, true) } }

        sig { params(payout: T.nilable(Models::Components::FeePaidBy)).void }
        def initialize(payout: nil)
          @payout = payout
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @payout == other.payout
          true
        end
      end
    end
  end
end
