# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Moov
  module Models
    module Components

      class UpdateTicketStatus < T::Enum
        enums do
          CLOSED = new('closed')
        end
      end
    end
  end
end
