# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Moov
  module Models
    module Components
      # VerificationStatus - Possible states an account verification can be in.
      #
      # @deprecated class: This will be removed in a future release, please migrate away from it as soon as possible.
      class VerificationStatus
        include ::Crystalline::Enum
        enums do
          UNVERIFIED = new('unverified')
          PENDING = new('pending')
          VERIFIED = new('verified')
          ERRORED = new('errored')
        end
        open!
      end
    end
  end
end
