# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Moov
  module Models
    module Components

      class WalletTransactionSourceType < T::Enum
        enums do
          TRANSFER = new('transfer')
          DISPUTE = new('dispute')
          ISSUING_CARD_TRANSACTION = new('issuing-card-transaction')
          ISSUING_AUTHORIZATION = new('issuing-authorization')
          SWEEP = new('sweep')
          ADJUSTMENT = new('adjustment')
          FEE = new('fee')
          RESIDUAL = new('residual')
        end
      end
    end
  end
end
