# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Moov
  module Models
    module Components
      # WebhookEventType - The type of event that occurred.
      class WebhookEventType < T::Enum


        enums do
          WILDCARD_ = new('*')
          ACCOUNT_CREATED = new('account.created')
          ACCOUNT_UPDATED = new('account.updated')
          ACCOUNT_DISCONNECTED = new('account.disconnected')
          BALANCE_UPDATED = new('balance.updated')
          BANK_ACCOUNT_CREATED = new('bankAccount.created')
          BANK_ACCOUNT_UPDATED = new('bankAccount.updated')
          BANK_ACCOUNT_DELETED = new('bankAccount.deleted')
          CANCELLATION_CREATED = new('cancellation.created')
          CANCELLATION_UPDATED = new('cancellation.updated')
          CARD_AUTO_UPDATED = new('card.autoUpdated')
          CAPABILITY_REQUESTED = new('capability.requested')
          CAPABILITY_UPDATED = new('capability.updated')
          DISPUTE_CREATED = new('dispute.created')
          DISPUTE_UPDATED = new('dispute.updated')
          INVOICE_CREATED = new('invoice.created')
          INVOICE_UPDATED = new('invoice.updated')
          NETWORK_ID_UPDATED = new('networkID.updated')
          PAYMENT_METHOD_ENABLED = new('paymentMethod.enabled')
          PAYMENT_METHOD_DISABLED = new('paymentMethod.disabled')
          REFUND_CREATED = new('refund.created')
          REFUND_UPDATED = new('refund.updated')
          REPRESENTATIVE_CREATED = new('representative.created')
          REPRESENTATIVE_UPDATED = new('representative.updated')
          REPRESENTATIVE_DELETED = new('representative.deleted')
          SWEEP_CREATED = new('sweep.created')
          SWEEP_UPDATED = new('sweep.updated')
          TERMINAL_APPLICATION_CREATED = new('terminalApplication.created')
          TERMINAL_APPLICATION_UPDATED = new('terminalApplication.updated')
          TICKET_CREATED = new('ticket.created')
          TICKET_UPDATED = new('ticket.updated')
          TICKET_MESSAGE_ADDED = new('ticket.messageAdded')
          TRANSFER_CREATED = new('transfer.created')
          TRANSFER_UPDATED = new('transfer.updated')
          WALLET_CREATED = new('wallet.created')
          WALLET_UPDATED = new('wallet.updated')
          WALLET_TRANSACTION_UPDATED = new('walletTransaction.updated')
          BILLING_STATEMENT_CREATED = new('billingStatement.created')
        end
      end
    end
  end
end
