# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Moov
  module Models
    module Components
    

      class WebhookDataSweepUpdated
        extend T::Sig
        include Crystalline::MetadataFields


        field :wallet_id, ::String, { 'format_json': { 'letter_case': ::Moov::Utils.field_name('walletID'), required: true } }

        field :sweep_id, ::String, { 'format_json': { 'letter_case': ::Moov::Utils.field_name('sweepID'), required: true } }

        field :status, Models::Components::SweepStatus, { 'format_json': { 'letter_case': ::Moov::Utils.field_name('status'), required: true, 'decoder': Utils.enum_from_string(Models::Components::SweepStatus, false) } }

        field :transfer_id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Moov::Utils.field_name('transferID') } }

        sig { params(wallet_id: ::String, sweep_id: ::String, status: Models::Components::SweepStatus, transfer_id: T.nilable(::String)).void }
        def initialize(wallet_id:, sweep_id:, status:, transfer_id: nil)
          @wallet_id = wallet_id
          @sweep_id = sweep_id
          @status = status
          @transfer_id = transfer_id
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @wallet_id == other.wallet_id
          return false unless @sweep_id == other.sweep_id
          return false unless @status == other.status
          return false unless @transfer_id == other.transfer_id
          true
        end
      end
    end
  end
end
