# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Moov
  module Models
    module Components
    

      class WebhookBillingStatementCreated
        extend T::Sig
        include Crystalline::MetadataFields


        field :statement_id, ::String, { 'format_json': { 'letter_case': ::Moov::Utils.field_name('statementID'), required: true } }

        sig { params(statement_id: ::String).void }
        def initialize(statement_id:)
          @statement_id = statement_id
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @statement_id == other.statement_id
          true
        end
      end
    end
  end
end
