# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Moov
  module Models
    module Operations

      class CreateAuthorizationSimulationResponse
        extend T::Sig
        include Crystalline::MetadataFields

        # HTTP response content type for this operation
        field :content_type, ::String
        # HTTP response status code for this operation
        field :status_code, ::Integer
        # Raw HTTP response; suitable for custom response parsing
        field :raw_response, ::Faraday::Response

        field :headers, Crystalline::Hash.new(Symbol, Crystalline::Array.new(::String))
        # The request completed successfully.
        field :issued_card_authorization, Crystalline::Nilable.new(Models::Components::IssuedCardAuthorization)
        # The resource was successfully accepted.
        field :authorization_simulation_async_response, Crystalline::Nilable.new(Models::Components::AuthorizationSimulationAsyncResponse)

        sig { params(content_type: ::String, status_code: ::Integer, raw_response: ::Faraday::Response, headers: T::Hash[Symbol, T::Array[::String]], issued_card_authorization: T.nilable(Models::Components::IssuedCardAuthorization), authorization_simulation_async_response: T.nilable(Models::Components::AuthorizationSimulationAsyncResponse)).void }
        def initialize(content_type:, status_code:, raw_response:, headers:, issued_card_authorization: nil, authorization_simulation_async_response: nil)
          @content_type = content_type
          @status_code = status_code
          @raw_response = raw_response
          @headers = headers
          @issued_card_authorization = issued_card_authorization
          @authorization_simulation_async_response = authorization_simulation_async_response
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @content_type == other.content_type
          return false unless @status_code == other.status_code
          return false unless @raw_response == other.raw_response
          return false unless @headers == other.headers
          return false unless @issued_card_authorization == other.issued_card_authorization
          return false unless @authorization_simulation_async_response == other.authorization_simulation_async_response
          true
        end
      end
    end
  end
end
