# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Moov
  module Models
    module Operations

      class DeleteDisputeEvidenceFileRequest
        extend T::Sig
        include Crystalline::MetadataFields


        field :account_id, ::String, { 'path_param': { 'field_name': 'accountID', 'style': 'simple', 'explode': false } }

        field :dispute_id, ::String, { 'path_param': { 'field_name': 'disputeID', 'style': 'simple', 'explode': false } }

        field :evidence_id, ::String, { 'path_param': { 'field_name': 'evidenceID', 'style': 'simple', 'explode': false } }

        sig { params(account_id: ::String, dispute_id: ::String, evidence_id: ::String).void }
        def initialize(account_id:, dispute_id:, evidence_id:)
          @account_id = account_id
          @dispute_id = dispute_id
          @evidence_id = evidence_id
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @account_id == other.account_id
          return false unless @dispute_id == other.dispute_id
          return false unless @evidence_id == other.evidence_id
          true
        end
      end
    end
  end
end
