# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Moov
  module Models
    module Operations

      class DisableWebhookRequest
        extend T::Sig
        include Crystalline::MetadataFields


        field :webhook_id, ::String, { 'path_param': { 'field_name': 'webhookID', 'style': 'simple', 'explode': false } }

        sig { params(webhook_id: ::String).void }
        def initialize(webhook_id:)
          @webhook_id = webhook_id
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @webhook_id == other.webhook_id
          true
        end
      end
    end
  end
end
