# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Moov
  module Models
    module Operations

      class GetDisputeEvidenceDataResponse
        extend T::Sig
        include Crystalline::MetadataFields

        # HTTP response content type for this operation
        field :content_type, ::String
        # HTTP response status code for this operation
        field :status_code, ::Integer
        # Raw HTTP response; suitable for custom response parsing
        field :raw_response, ::Faraday::Response

        field :headers, Crystalline::Hash.new(Symbol, Crystalline::Array.new(::String))
        # The request has succeeded.
        field :two_hundred_application_pdf_bytes, Crystalline::Nilable.new(::String)
        # The request has succeeded.
        field :two_hundred_image_jpeg_bytes, Crystalline::Nilable.new(::String)
        # The request has succeeded.
        field :two_hundred_image_tiff_bytes, Crystalline::Nilable.new(::String)

        sig { params(content_type: ::String, status_code: ::Integer, raw_response: ::Faraday::Response, headers: T::Hash[Symbol, T::Array[::String]], two_hundred_application_pdf_bytes: T.nilable(::String), two_hundred_image_jpeg_bytes: T.nilable(::String), two_hundred_image_tiff_bytes: T.nilable(::String)).void }
        def initialize(content_type:, status_code:, raw_response:, headers:, two_hundred_application_pdf_bytes: nil, two_hundred_image_jpeg_bytes: nil, two_hundred_image_tiff_bytes: nil)
          @content_type = content_type
          @status_code = status_code
          @raw_response = raw_response
          @headers = headers
          @two_hundred_application_pdf_bytes = two_hundred_application_pdf_bytes
          @two_hundred_image_jpeg_bytes = two_hundred_image_jpeg_bytes
          @two_hundred_image_tiff_bytes = two_hundred_image_tiff_bytes
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @content_type == other.content_type
          return false unless @status_code == other.status_code
          return false unless @raw_response == other.raw_response
          return false unless @headers == other.headers
          return false unless @two_hundred_application_pdf_bytes == other.two_hundred_application_pdf_bytes
          return false unless @two_hundred_image_jpeg_bytes == other.two_hundred_image_jpeg_bytes
          return false unless @two_hundred_image_tiff_bytes == other.two_hundred_image_tiff_bytes
          true
        end
      end
    end
  end
end
