# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Moov
  module Models
    module Operations

      class GetIssuedCardTransactionRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # The Moov business account for which cards have been issued.
        field :account_id, ::String, { 'path_param': { 'field_name': 'accountID', 'style': 'simple', 'explode': false } }

        field :card_transaction_id, ::String, { 'path_param': { 'field_name': 'cardTransactionID', 'style': 'simple', 'explode': false } }

        sig { params(account_id: ::String, card_transaction_id: ::String).void }
        def initialize(account_id:, card_transaction_id:)
          @account_id = account_id
          @card_transaction_id = card_transaction_id
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @account_id == other.account_id
          return false unless @card_transaction_id == other.card_transaction_id
          true
        end
      end
    end
  end
end
