# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Moov
  module Models
    module Operations

      class InitiateBankAccountVerificationRequest
        extend T::Sig
        include Crystalline::MetadataFields


        field :account_id, ::String, { 'path_param': { 'field_name': 'accountID', 'style': 'simple', 'explode': false } }

        field :bank_account_id, ::String, { 'path_param': { 'field_name': 'bankAccountID', 'style': 'simple', 'explode': false } }
        # Optional header to wait for certain events, such as the rail response, to occur before returning a response.
        #
        # When this header is set to `rail-response`, the endpoint will wait for a sent-credit or failed status from the payment rail.
        field :x_wait_for, Crystalline::Nilable.new(Models::Components::BankAccountWaitFor), { 'header': { 'field_name': 'x-wait-for', 'style': 'simple', 'explode': false } }

        sig { params(account_id: ::String, bank_account_id: ::String, x_wait_for: T.nilable(Models::Components::BankAccountWaitFor)).void }
        def initialize(account_id:, bank_account_id:, x_wait_for: nil)
          @account_id = account_id
          @bank_account_id = bank_account_id
          @x_wait_for = x_wait_for
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @account_id == other.account_id
          return false unless @bank_account_id == other.bank_account_id
          return false unless @x_wait_for == other.x_wait_for
          true
        end
      end
    end
  end
end
