# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Moov
  module Models
    module Operations

      class InitiateMicroDepositsRequest
        extend T::Sig
        include Crystalline::MetadataFields


        field :account_id, ::String, { 'path_param': { 'field_name': 'accountID', 'style': 'simple', 'explode': false } }

        field :bank_account_id, ::String, { 'path_param': { 'field_name': 'bankAccountID', 'style': 'simple', 'explode': false } }

        sig { params(account_id: ::String, bank_account_id: ::String).void }
        def initialize(account_id:, bank_account_id:)
          @account_id = account_id
          @bank_account_id = bank_account_id
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @account_id == other.account_id
          return false unless @bank_account_id == other.bank_account_id
          true
        end
      end
    end
  end
end
