# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Moov
  module Models
    module Operations

      class LinkApplePayTokenResponse
        extend T::Sig
        include Crystalline::MetadataFields

        # HTTP response content type for this operation
        field :content_type, ::String
        # HTTP response status code for this operation
        field :status_code, ::Integer
        # Raw HTTP response; suitable for custom response parsing
        field :raw_response, ::Faraday::Response

        field :headers, Crystalline::Hash.new(Symbol, Crystalline::Array.new(::String))
        # The request completed successfully.
        field :linked_apple_pay_payment_method, Crystalline::Nilable.new(Models::Components::LinkedApplePayPaymentMethod)

        sig { params(content_type: ::String, status_code: ::Integer, raw_response: ::Faraday::Response, headers: T::Hash[Symbol, T::Array[::String]], linked_apple_pay_payment_method: T.nilable(Models::Components::LinkedApplePayPaymentMethod)).void }
        def initialize(content_type:, status_code:, raw_response:, headers:, linked_apple_pay_payment_method: nil)
          @content_type = content_type
          @status_code = status_code
          @raw_response = raw_response
          @headers = headers
          @linked_apple_pay_payment_method = linked_apple_pay_payment_method
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @content_type == other.content_type
          return false unless @status_code == other.status_code
          return false unless @raw_response == other.raw_response
          return false unless @headers == other.headers
          return false unless @linked_apple_pay_payment_method == other.linked_apple_pay_payment_method
          true
        end
      end
    end
  end
end
