# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Moov
  module Models
    module Operations

      class LinkCardRequest
        extend T::Sig
        include Crystalline::MetadataFields


        field :account_id, ::String, { 'path_param': { 'field_name': 'accountID', 'style': 'simple', 'explode': false } }

        field :link_card, Models::Components::LinkCard, { 'request': { 'media_type': 'application/json' } }
        # Optional header to wait for certain events, such as the creation of a payment method, to occur before returning a response.
        #
        # When this header is set to `payment-method`, the response will include any payment methods that were created for the newly 
        # linked card in the `paymentMethods` field. Otherwise, the `paymentMethods` field will be omitted from the response.
        field :x_wait_for, Crystalline::Nilable.new(Models::Components::LinkCardWaitFor), { 'header': { 'field_name': 'x-wait-for', 'style': 'simple', 'explode': false } }

        sig { params(account_id: ::String, link_card: Models::Components::LinkCard, x_wait_for: T.nilable(Models::Components::LinkCardWaitFor)).void }
        def initialize(account_id:, link_card:, x_wait_for: nil)
          @account_id = account_id
          @link_card = link_card
          @x_wait_for = x_wait_for
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @account_id == other.account_id
          return false unless @link_card == other.link_card
          return false unless @x_wait_for == other.x_wait_for
          true
        end
      end
    end
  end
end
