# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Moov
  module Models
    module Operations

      class ListFeePlansResponse
        extend T::Sig
        include Crystalline::MetadataFields

        # HTTP response content type for this operation
        field :content_type, ::String
        # HTTP response status code for this operation
        field :status_code, ::Integer
        # Raw HTTP response; suitable for custom response parsing
        field :raw_response, ::Faraday::Response

        field :headers, Crystalline::Hash.new(Symbol, Crystalline::Array.new(::String))
        # The request completed successfully.
        field :fee_plans, Crystalline::Nilable.new(Crystalline::Array.new(Models::Components::FeePlan))

        sig { params(content_type: ::String, status_code: ::Integer, raw_response: ::Faraday::Response, headers: T::Hash[Symbol, T::Array[::String]], fee_plans: T.nilable(T::Array[Models::Components::FeePlan])).void }
        def initialize(content_type:, status_code:, raw_response:, headers:, fee_plans: nil)
          @content_type = content_type
          @status_code = status_code
          @raw_response = raw_response
          @headers = headers
          @fee_plans = fee_plans
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @content_type == other.content_type
          return false unless @status_code == other.status_code
          return false unless @raw_response == other.raw_response
          return false unless @headers == other.headers
          return false unless @fee_plans == other.fee_plans
          true
        end
      end
    end
  end
end
