# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Moov
  module Models
    module Operations

      class ListInvoicesRequest
        extend T::Sig
        include Crystalline::MetadataFields


        field :account_id, ::String, { 'path_param': { 'field_name': 'accountID', 'style': 'simple', 'explode': false } }
        # Specify an API version.
        #
        # API versioning follows the format `vYYYY.QQ.BB`, where 
        #   - `YYYY` is the year
        #   - `QQ` is the two-digit month for the first month of the quarter (e.g., 01, 04, 07, 10)
        #   - `BB` is the build number, starting at `.01`, for subsequent builds in the same quarter. 
        #     - For example, `v2024.01.00` is the initial release of the first quarter of 2024.
        #
        # The `dev` version represents the most recent development state. It may include breaking changes and should be treated as a beta release.
        # When no version is specified, the API defaults to `v2024.01.00`.
        field :x_moov_version, Crystalline::Nilable.new(::String), { 'header': { 'field_name': 'X-Moov-Version', 'style': 'simple', 'explode': false } }

        field :skip, Crystalline::Nilable.new(::Integer), { 'query_param': { 'field_name': 'skip', 'style': 'form', 'explode': false } }

        field :count, Crystalline::Nilable.new(::Integer), { 'query_param': { 'field_name': 'count', 'style': 'form', 'explode': false } }

        field :status, Crystalline::Nilable.new(Models::Components::InvoiceStatus), { 'query_param': { 'field_name': 'status', 'style': 'form', 'explode': false } }

        field :customer_account_id, Crystalline::Nilable.new(::String), { 'query_param': { 'field_name': 'customerAccountID', 'style': 'form', 'explode': false } }

        field :created_start_date_time, Crystalline::Nilable.new(::DateTime), { 'query_param': { 'field_name': 'createdStartDateTime', 'style': 'form', 'explode': false } }

        field :created_end_date_time, Crystalline::Nilable.new(::DateTime), { 'query_param': { 'field_name': 'createdEndDateTime', 'style': 'form', 'explode': false } }

        field :due_start_date_time, Crystalline::Nilable.new(::DateTime), { 'query_param': { 'field_name': 'dueStartDateTime', 'style': 'form', 'explode': false } }

        field :due_end_date_time, Crystalline::Nilable.new(::DateTime), { 'query_param': { 'field_name': 'dueEndDateTime', 'style': 'form', 'explode': false } }

        sig { params(account_id: ::String, x_moov_version: T.nilable(::String), skip: T.nilable(::Integer), count: T.nilable(::Integer), status: T.nilable(Models::Components::InvoiceStatus), customer_account_id: T.nilable(::String), created_start_date_time: T.nilable(::DateTime), created_end_date_time: T.nilable(::DateTime), due_start_date_time: T.nilable(::DateTime), due_end_date_time: T.nilable(::DateTime)).void }
        def initialize(account_id:, x_moov_version: nil, skip: nil, count: nil, status: nil, customer_account_id: nil, created_start_date_time: nil, created_end_date_time: nil, due_start_date_time: nil, due_end_date_time: nil)
          @account_id = account_id
          @x_moov_version = x_moov_version
          @skip = skip
          @count = count
          @status = status
          @customer_account_id = customer_account_id
          @created_start_date_time = created_start_date_time
          @created_end_date_time = created_end_date_time
          @due_start_date_time = due_start_date_time
          @due_end_date_time = due_end_date_time
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @account_id == other.account_id
          return false unless @x_moov_version == other.x_moov_version
          return false unless @skip == other.skip
          return false unless @count == other.count
          return false unless @status == other.status
          return false unless @customer_account_id == other.customer_account_id
          return false unless @created_start_date_time == other.created_start_date_time
          return false unless @created_end_date_time == other.created_end_date_time
          return false unless @due_start_date_time == other.due_start_date_time
          return false unless @due_end_date_time == other.due_end_date_time
          true
        end
      end
    end
  end
end
