# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Moov
  module Models
    module Operations

      class RequestCapabilitiesRequest
        extend T::Sig
        include Crystalline::MetadataFields


        field :account_id, ::String, { 'path_param': { 'field_name': 'accountID', 'style': 'simple', 'explode': false } }

        field :add_capabilities, Models::Components::AddCapabilities, { 'request': { 'media_type': 'application/json' } }

        sig { params(account_id: ::String, add_capabilities: Models::Components::AddCapabilities).void }
        def initialize(account_id:, add_capabilities:)
          @account_id = account_id
          @add_capabilities = add_capabilities
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @account_id == other.account_id
          return false unless @add_capabilities == other.add_capabilities
          true
        end
      end
    end
  end
end
