# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Moov
  module Models
    module Operations

      class UpdateTransferRequest
        extend T::Sig
        include Crystalline::MetadataFields

        # Identifier for the transfer.
        field :transfer_id, ::String, { 'path_param': { 'field_name': 'transferID', 'style': 'simple', 'explode': false } }

        field :account_id, ::String, { 'path_param': { 'field_name': 'accountID', 'style': 'simple', 'explode': false } }

        field :patch_transfer, Models::Components::PatchTransfer, { 'request': { 'media_type': 'application/json' } }

        sig { params(transfer_id: ::String, account_id: ::String, patch_transfer: Models::Components::PatchTransfer).void }
        def initialize(transfer_id:, account_id:, patch_transfer:)
          @transfer_id = transfer_id
          @account_id = account_id
          @patch_transfer = patch_transfer
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @transfer_id == other.transfer_id
          return false unless @account_id == other.account_id
          return false unless @patch_transfer == other.patch_transfer
          true
        end
      end
    end
  end
end
