# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Moov
  module Models
    module Operations

      class UpdateDisputeEvidenceRequest
        extend T::Sig
        include Crystalline::MetadataFields


        field :account_id, ::String, { 'path_param': { 'field_name': 'accountID', 'style': 'simple', 'explode': false } }

        field :dispute_id, ::String, { 'path_param': { 'field_name': 'disputeID', 'style': 'simple', 'explode': false } }

        field :evidence_id, ::String, { 'path_param': { 'field_name': 'evidenceID', 'style': 'simple', 'explode': false } }

        field :update_evidence, Models::Components::UpdateEvidence, { 'request': { 'media_type': 'application/json' } }

        sig { params(account_id: ::String, dispute_id: ::String, evidence_id: ::String, update_evidence: Models::Components::UpdateEvidence).void }
        def initialize(account_id:, dispute_id:, evidence_id:, update_evidence:)
          @account_id = account_id
          @dispute_id = dispute_id
          @evidence_id = evidence_id
          @update_evidence = update_evidence
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @account_id == other.account_id
          return false unless @dispute_id == other.dispute_id
          return false unless @evidence_id == other.evidence_id
          return false unless @update_evidence == other.update_evidence
          true
        end
      end
    end
  end
end
