workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    latest:
        inputs:
            - location: registry.speakeasyapi.dev/moov/moov/api-latest
        registry:
            location: registry.speakeasyapi.dev/moov/moov/latest
targets:
    moov:
        target: ruby
        source: latest
        publish:
            rubygems:
                token: $rubygems_auth_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/moov/moov/latest-ruby-code-samples
            labelOverride:
                fixedValue: Ruby (SDK)
            blocking: false
