workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    latest:
        inputs:
            - location: registry.speakeasyapi.dev/moov/moov/api-v2026.01.00
        registry:
            location: registry.speakeasyapi.dev/moov/moov/ruby-v2026.01.00
targets:
    moov:
        target: ruby
        source: latest
        publish:
            rubygems:
                token: $rubygems_auth_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/moov/moov/v2026.01.00-ruby-code-samples
            labelOverride:
                fixedValue: Ruby (SDK)
            blocking: false
