# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Moov
  module Models
    module Errors

      class CreateAccountError < StandardError
        extend T::Sig
        include Crystalline::MetadataFields


        field :account_type, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Moov::Utils.field_name('accountType') } }

        field :profile, Crystalline::Nilable.new(Models::Components::CreateProfileError), { 'format_json': { 'letter_case': ::Moov::Utils.field_name('profile') } }

        field :metadata, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Moov::Utils.field_name('metadata') } }

        field :terms_of_service, Crystalline::Nilable.new(Models::Components::TermsOfServiceError), { 'format_json': { 'letter_case': ::Moov::Utils.field_name('termsOfService') } }

        field :foreign_id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Moov::Utils.field_name('foreignID') } }

        field :customer_support, Crystalline::Nilable.new(Models::Components::CustomerSupportError), { 'format_json': { 'letter_case': ::Moov::Utils.field_name('customerSupport') } }

        field :settings, Crystalline::Nilable.new(Models::Components::CreateAccountSettings), { 'format_json': { 'letter_case': ::Moov::Utils.field_name('settings') } }

        field :capabilities, Crystalline::Nilable.new(Crystalline::Hash.new(Symbol, ::String)), { 'format_json': { 'letter_case': ::Moov::Utils.field_name('capabilities') } }
        # Raw HTTP response; suitable for custom response parsing
        field :raw_response, Crystalline::Nilable.new(::Faraday::Response), { 'format_json': { 'letter_case': ::Moov::Utils.field_name('-') } }

        sig { params(account_type: T.nilable(::String), profile: T.nilable(Models::Components::CreateProfileError), metadata: T.nilable(::String), terms_of_service: T.nilable(Models::Components::TermsOfServiceError), foreign_id: T.nilable(::String), customer_support: T.nilable(Models::Components::CustomerSupportError), settings: T.nilable(Models::Components::CreateAccountSettings), capabilities: T.nilable(T::Hash[Symbol, ::String]), raw_response: T.nilable(::Faraday::Response)).void }
        def initialize(account_type: nil, profile: nil, metadata: nil, terms_of_service: nil, foreign_id: nil, customer_support: nil, settings: nil, capabilities: nil, raw_response: nil)
          @account_type = account_type
          @profile = profile
          @metadata = metadata
          @terms_of_service = terms_of_service
          @foreign_id = foreign_id
          @customer_support = customer_support
          @settings = settings
          @capabilities = capabilities
          @raw_response = raw_response
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @account_type == other.account_type
          return false unless @profile == other.profile
          return false unless @metadata == other.metadata
          return false unless @terms_of_service == other.terms_of_service
          return false unless @foreign_id == other.foreign_id
          return false unless @customer_support == other.customer_support
          return false unless @settings == other.settings
          return false unless @capabilities == other.capabilities
          return false unless @raw_response == other.raw_response
          true
        end
      end
    end
  end
end
