# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Moov
  module Models
    module Errors
    

      class FeePlanAgreementError
        extend T::Sig
        include Crystalline::MetadataFields


        field :plan_id, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Moov::Utils.field_name('planID') } }
        # Raw HTTP response; suitable for custom response parsing
        field :raw_response, Crystalline::Nilable.new(::Faraday::Response), { 'format_json': { 'letter_case': ::Moov::Utils.field_name('-') } }

        sig { params(plan_id: T.nilable(::String), raw_response: T.nilable(::Faraday::Response)).void }
        def initialize(plan_id: nil, raw_response: nil)
          @plan_id = plan_id
          @raw_response = raw_response
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @plan_id == other.plan_id
          return false unless @raw_response == other.raw_response
          true
        end
      end
    end
  end
end
