# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Moov
  module Models
    module Errors
    

      class ListWalletsValidationError < StandardError
        extend T::Sig
        include Crystalline::MetadataFields


        field :status, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Moov::Utils.field_name('status') } }

        field :wallet_type, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Moov::Utils.field_name('walletType') } }

        field :skip, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Moov::Utils.field_name('skip') } }

        field :count, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Moov::Utils.field_name('count') } }
        # Raw HTTP response; suitable for custom response parsing
        field :raw_response, Crystalline::Nilable.new(::Faraday::Response), { 'format_json': { 'letter_case': ::Moov::Utils.field_name('-') } }

        sig { params(status: T.nilable(::String), wallet_type: T.nilable(::String), skip: T.nilable(::String), count: T.nilable(::String), raw_response: T.nilable(::Faraday::Response)).void }
        def initialize(status: nil, wallet_type: nil, skip: nil, count: nil, raw_response: nil)
          @status = status
          @wallet_type = wallet_type
          @skip = skip
          @count = count
          @raw_response = raw_response
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @status == other.status
          return false unless @wallet_type == other.wallet_type
          return false unless @skip == other.skip
          return false unless @count == other.count
          return false unless @raw_response == other.raw_response
          true
        end
      end
    end
  end
end
