# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Moov
  module Models
    module Errors
    

      class TransferOptionsValidationError < StandardError
        extend T::Sig
        include Crystalline::MetadataFields


        field :amount, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Moov::Utils.field_name('amount') } }

        field :source, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Moov::Utils.field_name('source') } }

        field :destination, Crystalline::Nilable.new(::String), { 'format_json': { 'letter_case': ::Moov::Utils.field_name('destination') } }
        # Raw HTTP response; suitable for custom response parsing
        field :raw_response, Crystalline::Nilable.new(::Faraday::Response), { 'format_json': { 'letter_case': ::Moov::Utils.field_name('-') } }

        sig { params(amount: T.nilable(::String), source: T.nilable(::String), destination: T.nilable(::String), raw_response: T.nilable(::Faraday::Response)).void }
        def initialize(amount: nil, source: nil, destination: nil, raw_response: nil)
          @amount = amount
          @source = source
          @destination = destination
          @raw_response = raw_response
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @amount == other.amount
          return false unless @source == other.source
          return false unless @destination == other.destination
          return false unless @raw_response == other.raw_response
          true
        end
      end
    end
  end
end
