# Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

# typed: true
# frozen_string_literal: true


module Moov
  module Models
    module Errors
    

      class UpdateUnderwritingError
        extend T::Sig
        include Crystalline::MetadataFields


        field :error, Models::Components::UpdateUnderwritingErrorError, { 'format_json': { 'letter_case': ::Moov::Utils.field_name('error'), required: true } }
        # Raw HTTP response; suitable for custom response parsing
        field :raw_response, Crystalline::Nilable.new(::Faraday::Response), { 'format_json': { 'letter_case': ::Moov::Utils.field_name('-') } }

        sig { params(error: Models::Components::UpdateUnderwritingErrorError, raw_response: T.nilable(::Faraday::Response)).void }
        def initialize(error:, raw_response: nil)
          @error = error
          @raw_response = raw_response
        end

        sig { params(other: T.untyped).returns(T::Boolean) }
        def ==(other)
          return false unless other.is_a? self.class
          return false unless @error == other.error
          return false unless @raw_response == other.raw_response
          true
        end
      end
    end
  end
end
